services:
  postgres:
    image: postgres:15.6-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
      - "8001:8001"

